// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/northbound/proto/diags.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/northbound/proto/diags.proto", fileDescriptor_c7617167392ea9d7) }

var fileDescriptor_c7617167392ea9d7 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4e, 0xd7,
	0xcf, 0xcb, 0x2f, 0x2a, 0xc9, 0x48, 0xca, 0x2f, 0xcd, 0x4b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x4f, 0xc9, 0x4c, 0x4c, 0x2f, 0xd6, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x11, 0x1f, 0x17,
	0x8f, 0x73, 0x7e, 0x5e, 0x49, 0x51, 0x7e, 0x8e, 0x0b, 0x48, 0x32, 0x89, 0x0d, 0x2c, 0x6c, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xe0, 0x6b, 0x99, 0x41, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlDiagsClient is the client API for ControlDiags service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlDiagsClient interface {
}

type controlDiagsClient struct {
	cc *grpc.ClientConn
}

func NewControlDiagsClient(cc *grpc.ClientConn) ControlDiagsClient {
	return &controlDiagsClient{cc}
}

// ControlDiagsServer is the server API for ControlDiags service.
type ControlDiagsServer interface {
}

// UnimplementedControlDiagsServer can be embedded to have forward compatible implementations.
type UnimplementedControlDiagsServer struct {
}

func RegisterControlDiagsServer(s *grpc.Server, srv ControlDiagsServer) {
	s.RegisterService(&_ControlDiags_serviceDesc, srv)
}

var _ControlDiags_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ControlDiags",
	HandlerType: (*ControlDiagsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/northbound/proto/diags.proto",
}
