# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Master workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    build-and-test:
      uses: onosproject/.github/.github/workflows/go-build-test.yml@main

  lint:
    uses: onosproject/.github/.github/workflows/go-lint.yml@main

  license-check:
    uses: onosproject/.github/.github/workflows/license-check.yml@main

  fossa-check:
    uses: onosproject/.github/.github/workflows/fossa-scan.yml@main
